### ISSUE TITLE
[Examples][DO] Example does not work

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-ansible-bigip#3]
There are some issues with the DO example i believe: 

https://github.com/f5devcentral/f5-ansible-bigip/blob/master/docs/examples/do_basics/do_basics.yaml has a typo. Tags is not properly aligned and it will make the playbook fail: 

```
- name: DO
  hosts: bigip
  connection: httpapi
  gather_facts: false

  tasks:   

    - name: Deploy DO Declaration
      f5networks.f5_bigip.bigip_do_deploy:
        content: "{{ lookup('file', 'declarations/do.json') }}"
        tags: [ deploy ]
``` 

it should be 

```
- name: DO
  hosts: bigip
  connection: httpapi
  gather_facts: false

  tasks:   

    - name: Deploy DO Declaration
      f5networks.f5_bigip.bigip_do_deploy:
        content: "{{ lookup('file', 'declarations/do.json') }}"
      tags: [ deploy ] 
```

Even when this is fixed, the example will fail: 

``` 
(Ansible) PAR-ML-00026375:examples menant$ ansible-playbook -i hosts do_basics/do_basics.yaml

PLAY [DO] ********************************************************************************************************************************************

TASK [Deploy DO Declaration] *************************************************************************************************************************
[WARNING]: Platform darwin on host bigip is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change the meaning of that path. See https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more
information.
fatal: [bigip]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Server parameter cannot be None or missing, please provide a valid value"}

PLAY RECAP *******************************************************************************************************************************************
bigip                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
``` 

it feels like DO is not using the same parameter as AS3 and TS. and the host_vars/bigip.yaml file is incomplete for DO
